### ISSUE TITLE
Sensors with RTOS not working

### ISSUE THREAD

**Issue by ladislas** [leka/moti#31]
Using the sensors class in a thread doesn't give any results, no output are serial printed.

the strange thing is that everything works fine with the motors.

must investigate

**Comment by melki** [comment]
Indeed

Melchior de TOLDI
0637687789

**Comment by ladislas** [comment]
Ok, I found out what going on!

the output is a `String` that we `Serial.println();`. It seems like `ChibiOS` does not like the String object...

**Comment by ladislas** [comment]
I've got the confirmation that [ChibiOS doesn't like `String` objects](http://forum.arduino.cc/index.php?PHPSESSID=qgn0ddetsn8l91ujnq2mqbm856&topic=107801.msg855479#msg855479) because it uses `malloc/free`.

We can still use it by adding this to `void setup()` :

``` c++
    char stkVar;
    extern char* __malloc_heap_end;
    // allow 256 locations for loop() stack
    __malloc_heap_end = &stkVar - 256;
```

But this could cause future bugs. We are going back with the old way to send the data as `json`.
